version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres3
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    environment:
      POSTGRES_USER: postgres3
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests
    ports:
      - '5433:5432'